### ISSUE TITLE
Unsaved changes handling

### ISSUE THREAD

**Issue by xelarep** [gp-rank13/gp-lyrics-chords#8]
1) When  opening the preferences while the editor is open and has unsaved changes, the editor gets closed and all the changes get lost when closing the preferences. 

2) When I just closing the editor and reopen with unsaved changes, they are still there (OK). 

3) When changing a song, changes also get lost 

I would expect a warning for 1) and 3) 
For 1) I would expect the same content of the editor view as before entering preferences - even if they are not saved

**Comment by gp-rank13** [comment]
Issue (1) is resolved with [Build #27](https://github.com/gp-rank13/gp-lyrics-chords/actions)

**Comment by gp-rank13** [comment]
I won't implement any warning when changing songs, as I would never want to prevent a song change from occurring. Lost unsaved changes when changing songs is therefore unavoidable.
One small change in the release 1.0.12 is that the 'Save' button is only displayed in the Editor window if there have been changes made i.e. acts as an indicator that there are unsaved changes.
